coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 80%
        threshold: 5%
        informational: false
    patch:
      default:
        target: 70%
        threshold: 10%
        informational: false

comment:
  layout: "header, diff, flags, components, footer"
  behavior: default
  require_changes: false

ignore:
  - "tests/**"
  - "examples/**"
  - "scripts/**"
  - "**/__pycache__"
  - "**/*.pyc"
